/**
 * Türkçe oda adı yasaklı kelime listesi.
 * JSON kopyası: js/data/profanityTerms.json (Node/Express)
 * Sunucu: supabase/migrations/029_oda_adi_moderation.sql
 */
export const PROFANITY_TERMS = [
    'amk', 'amq', 'a.q',
    'siktir', 'sikerim', 'sikeyim', 'sikiyim', 'siktim', 'sikis', 'sikicem', 'sikecem',
    'siktirolgit', 'siktirgit', 'siktirlan', 'sikik', 'sikimsonik', 'sikimson', 'sikherif',
    'orospu', 'orosbu', 'orospucocugu', 'orospucocuk', 'orospunun',
    'pic', 'pich', 'pezevenk', 'pezeveng',
    'gotunu', 'gotune', 'gotveren', 'gavat', 'gavot',
    'yarrak', 'yarak', 'yarrag', 'yarrrak',
    'amcik', 'amcig', 'amkoyayim', 'amkoyim', 'amina', 'aminakoyim',
    'kahpe', 'kaltak', 'surtuk', 'fahise',
    'ibne', 'ibine', 'ibnelik',
    'gotveren', 'gotlalesi',
    'kufur', 'kufr',
    'salak', 'aptal', 'gerizekali', 'dangalak', 'ahmak', 'budala',
    'anan', 'anani', 'ananisikerim', 'ananisikiyim',
    'babani', 'bacini', 'sulaleni',
    'kahrol', 'kahrolsun',
    'defol', 'defolgit',
    'geber', 'geberesice',
    'hassiktir', 'hassiktirlan', 'hasiktir',
    'lanet', 'lanetolsun',
    'pust', 'pusht', 'pushtluk',
    'dalyarak', 'dalyarrak',
    'kavat', 'kavata',
    'serefsiz', 'namussuz', 'namussuzluk',
    'itoglu', 'kopek',
    'esek', 'okuz', 'domuz',
    'embesil', 'moron', 'idiot', 'idiyot',
    'porno', 'pornografi', 'seks', 'sikisme',
    'fuck', 'fucking', 'fucker', 'fck', 'fuk', 'fuking',
    'shit', 'bitch', 'asshole', 'bastard',
    'nigger', 'nigga', 'faggot', 'retard',
    'nazi', 'hitler', 'holokost', 'holocaust',
    'terorist', 'terrorist',
    's1ktir', 's1kerim', 'or0spu', 'am1k', 'y4rak', 'g0t',
    'sktr', 'sktrgit', 'sktir', 'sktirgit',
    'orsp', 'orspu', 'orsbu',
    'p1c', 'kahp', 'kaltk', 'kahbe',
];
