/**
 * YAZİYO — Kayıt için kabul edilen Türkçe ad / soyad listesi
 * Karşılaştırma Türkçe küçük harf ile yapılır (İ/i, I/ı).
 */

function toSet(list) {
    return new Set(list.map((n) => String(n).toLocaleLowerCase('tr-TR')));
}

const GIVEN_NAMES = [
    'Ahmet', 'Mehmet', 'Mustafa', 'Ali', 'Hüseyin', 'Hasan', 'İbrahim', 'İsmail', 'Osman', 'Yusuf',
    'Murat', 'Ömer', 'Ramazan', 'Halil', 'Süleyman', 'Abdullah', 'Mahmut', 'Recep', 'Salih', 'Kemal',
    'Fatih', 'Emre', 'Burak', 'Can', 'Cem', 'Cenk', 'Eren', 'Ege', 'Kaan', 'Emir',
    'Yiğit', 'Berk', 'Arda', 'Deniz', 'Barış', 'Onur', 'Serkan', 'Volkan', 'Hakan', 'Erkan',
    'Gökhan', 'Orhan', 'Tolga', 'Uğur', 'Levent', 'Tuncay', 'Cengiz', 'Erhan', 'Selim', 'Tarık',
    'Oğuz', 'Oğuzhan', 'Alper', 'Alperen', 'Furkan', 'Enes', 'Yasin', 'Mert', 'Kerem', 'Emirhan',
    'Berat', 'Efe', 'Özgür', 'Serhat', 'Sinan', 'Tuncer', 'Vedat', 'Zafer', 'Zeki', 'Yavuz',
    'Adem', 'Adnan', 'Akın', 'Alican', 'Alpay', 'Arif', 'Aydın', 'Ayhan', 'Bahadır', 'Bora',
    'Bülent', 'Cahit', 'Celal', 'Cemil', 'Coşkun', 'Doğan', 'Durmuş', 'Emin', 'Engin', 'Erdal',
    'Erdem', 'Erdoğan', 'Erol', 'Ertuğrul', 'Faruk', 'Ferhat', 'Fikret', 'Fuat', 'Gürkan', 'Halit',
    'Hamza', 'Harun', 'Hayati', 'Hidayet', 'İlhan', 'İlker', 'İlyas', 'İsa', 'Kadir', 'Kasım',
    'Kazım', 'Koray', 'Kutay', 'Lütfi', 'Mesut', 'Metin', 'Muhammet', 'Muhammed', 'Niyazi', 'Nuri',
    'Okan', 'Oktay', 'Önder', 'Özcan', 'Rıza', 'Rıdvan', 'Sabahattin', 'Saffet', 'Samet', 'Sedat',
    'Selçuk', 'Semih', 'Şaban', 'Şahin', 'Şerif', 'Şükrü', 'Taner', 'Tayfun', 'Tayyip', 'Tevfik',
    'Turgut', 'Ufuk', 'Ümit', 'Veli', 'Yalçın', 'Yılmaz', 'Ziya', 'Berkay', 'Batuhan', 'Doğukan',
    'Göktuğ', 'Kağan', 'Kuzey', 'Miraç', 'Ömerfaruk', 'Umut', 'Utku', 'Yunus', 'Zeynel', 'Bilal',
    'Cüneyt', 'Dursun', 'Ekrem', 'Enver', 'Ercan', 'Ferdi', 'Gökmen', 'Halis', 'Haydar', 'Hikmet',
    'İhsan', 'İzzet', 'Kamil', 'Kenan', 'Latif', 'Mazhar', 'Mithat', 'Muammer', 'Muharrem', 'Mücahit',
    'Namık', 'Necati', 'Necmettin', 'Numan', 'Nurettin', 'Okay', 'Özkan', 'Pertev', 'Rasim', 'Remzi',
    'Rüştü', 'Sadi', 'Sami', 'Sefer', 'Seyit', 'Suat', 'Şevket', 'Talat', 'Tanju', 'Tekin',
    'Temel', 'Turgay', 'Vecdi', 'Yahya', 'Yüksel', 'Zekeriya', 'Ata', 'Atlas', 'Aybars', 'Ayaz',
    'Bartu', 'Boraç', 'Çağan', 'Çağrı', 'Çınar', 'Doruk', 'Egehan', 'Eralp', 'Gökalp', 'Kutlu',
    'Mete', 'Metehan', 'Ozan', 'Poyraz', 'Rüzgar', 'Tuna', 'Tuğra', 'Yaman', 'Alp', 'Alparslan',
    'Atakan', 'Aykut', 'Bayram', 'Bekir', 'Bedirhan', 'Berke', 'Caner', 'Cihan', 'Çağlar', 'Dağhan',
    'Demir', 'Derya', 'Ercüment', 'Evren', 'Fırat', 'Göker', 'Güneş', 'Hüdai', 'İlter', 'Kaanalp',
    'Kutayhan', 'Miran', 'Nejat', 'Ömür', 'Polat', 'Rüzgaralp', 'Sarp', 'Satuk', 'Soner', 'Tamer',
    'Tan', 'Tarkan', 'Teoman', 'Timur', 'Toprak', 'Tuğrul', 'Ulaş', 'Umur', 'Ünal', 'Yekta',
    'Ayşe', 'Fatma', 'Emine', 'Hatice', 'Zeynep', 'Elif', 'Meryem', 'Şerife', 'Zehra', 'Sultan',
    'Hanife', 'Merve', 'Esra', 'Özlem', 'Sevgi', 'Yasemin', 'Hülya', 'Aysel', 'Dilek', 'Gül',
    'Hacer', 'Hava', 'Hayriye', 'Kadriye', 'Leyla', 'Melek', 'Naciye', 'Nazlı', 'Neriman', 'Nur',
    'Nuran', 'Nuray', 'Nuriye', 'Pınar', 'Seda', 'Sibel', 'Sinem', 'Songül', 'Şükran', 'Tülay',
    'Ülkü', 'Yıldız', 'Aslı', 'Aylin', 'Ayşegül', 'Bahar', 'Banu', 'Başak', 'Belgin', 'Berna',
    'Beste', 'Betül', 'Beyza', 'Bilge', 'Büşra', 'Cansu', 'Cemile', 'Ceren', 'Ceyda', 'Ceylan',
    'Çiğdem', 'Damla', 'Defne', 'Didem', 'Duygu', 'Ebru', 'Ece', 'Eda', 'Ekin', 'Elvan',
    'Emel', 'Esen', 'Eylül', 'Ezgi', 'Feride', 'Filiz', 'Fulya', 'Gamze', 'Gizem', 'Gönül',
    'Gülay', 'Gülcan', 'Gülçin', 'Gülden', 'Güler', 'Gülhan', 'Gülizar', 'Gülşah', 'Gülşen', 'Hale',
    'Hande', 'Hazal', 'Hilal', 'İclal', 'İlayda', 'İpek', 'İrem', 'Jale', 'Kübra', 'Lale',
    'Melike', 'Melis', 'Melisa', 'Meltem', 'Mine', 'Miray', 'Neslihan', 'Neşe', 'Nilay', 'Nilgün',
    'Nisa', 'Nurcan', 'Nurgül', 'Özge', 'Pelinsu', 'Pelin', 'Perihan', 'Rabia', 'Rana', 'Reyhan',
    'Rukiye', 'Safiye', 'Selin', 'Selma', 'Sema', 'Semiha', 'Serap', 'Serpil', 'Sevil', 'Sevim',
    'Sıla', 'Simge', 'Şeyma', 'Tuğba', 'Tuğçe', 'Türkan', 'Yelda', 'Yeşim', 'Yonca', 'Zahide',
    'Zeliha', 'Zümra', 'Ada', 'Aleyna', 'Almila', 'Arzu', 'Asya', 'Aydan', 'Aysun', 'Azra',
    'Belinay', 'Beril', 'Berra', 'Bihter', 'Buket', 'Burcu', 'Canan', 'Çağla', 'Derin', 'Dilan',
    'Doğa', 'Ecrin', 'Elanur', 'Elifnaz', 'Elisa', 'Emim', 'Erva', 'Esin', 'Fadime', 'Funda',
    'Gökçe', 'Gülizar', 'Hiranur', 'İkra', 'İlknur', 'İnci', 'Leman', 'Lina', 'Masal', 'Melekşah',
    'Mira', 'Narin', 'Naz', 'Nehir', 'Nesrin', 'Neva', 'Nil', 'Nisanur', 'Nisan', 'Öykü',
    'Parla', 'Rüya', 'Selena', 'Serra', 'Sezen', 'Su', 'Sude', 'Şevval', 'Tuğçe', 'Yağmur',
    'Zeynep', 'Zümrüt', 'Ahsen', 'Alara', 'Arya', 'Aysima', 'Berfin', 'Berilay', 'Cemre', 'Dilara',
    'Eflin', 'Eliz', 'Erva', 'Eslem', 'Hafsa', 'Hümeyra', 'İkbal', 'Lina', 'Melek', 'Meryem',
    'Nisanur', 'Rümeysa', 'Sema', 'Sümeyye', 'Şule', 'Tuana', 'Vildan', 'Yaren', 'Zeyna', 'Zişan',
    'Adil', 'Afra', 'Asım', 'Aybüke', 'Aysu', 'Aziz', 'Bedriye', 'Behice', 'Cahide', 'Cennet',
    'Dürdane', 'Edanur', 'Elanur', 'Emine', 'Esma', 'Fadime', 'Gülsüm', 'Hafize', 'Halime', 'Hamdiye',
    'Hümeyra', 'İffet', 'Kamile', 'Kezban', 'Medine', 'Mevlüde', 'Mukaddes', 'Münire', 'Nafiye', 'Naime',
    'Nazife', 'Nesibe', 'Nevriye', 'Nigar', 'Nurten', 'Pakize', 'Rahime', 'Refika', 'Saadet', 'Sabiha',
    'Sacide', 'Saime', 'Sare', 'Sebahat', 'Selime', 'Servet', 'Seher', 'Sidika', 'Şahinde', 'Şaziye',
    'Şennur', 'Tenzile', 'Teslime', 'Ümmühan', 'Vasfiye', 'Yurdanur', 'Zekiye', 'Zübeyde', 'Zümrüt',
    'Baran', 'Bedir', 'Cemal', 'Cihat', 'Çetin', 'Davut', 'Ertan', 'Fevzi', 'Gazanfer', 'Hüdai',
    'İdris', 'Kudret', 'Macit', 'Muzaffer', 'Necip', 'Nihat', 'Rauf', 'Saim', 'Sıtkı', 'Şevki',
    'Talha', 'Taha', 'Umutcan', 'Vahit', 'Yücel', 'Zülküf', 'Ebrar', 'Ela', 'Elçin', 'Feray',
    'Gülten', 'Hediye', 'İlke', 'Kumsal', 'Lamia', 'Mehtap', 'Nalan', 'Oya', 'Pembe', 'Rengin',
    'Selda', 'Tuba', 'Ümran', 'Vesile', 'Yasemin', 'Zara', 'Asude', 'Berivan', 'Canan', 'Dilay',
    'Ecem', 'Feyza', 'Gülbahar', 'Hümeyra', 'İclal', 'Jülide', 'Kader', 'Lütfiye', 'Menekşe', 'Nursel',
    'Özden', 'Pınar', 'Raziye', 'Sibel', 'Türkan', 'Ülker', 'Vildan', 'Yelda', 'Zuhal',
    'Sevda', 'Serdar', 'Cevdet', 'Nihal', 'Figen', 'Sevcan', 'Nihan', 'Burhan', 'Erdinç',
    'Asel', 'Ayşenur', 'Fatmanur', 'Elifnur', 'Mervenur', 'Esmanur', 'Nursima',
    'Eymen', 'Alperen', 'Göktuğ', 'Kuzey', 'Miran', 'Yiğit', 'Aras', 'Çınar', 'Doruk', 'Kaan'
];

const SURNAMES = [
    'Yılmaz', 'Kaya', 'Demir', 'Çelik', 'Şahin', 'Yıldız', 'Yıldırım', 'Öztürk', 'Aydın', 'Özdemir',
    'Arslan', 'Doğan', 'Kılıç', 'Aslan', 'Çetin', 'Kara', 'Koç', 'Kurt', 'Özkan', 'Şimşek',
    'Erdoğan', 'Aksoy', 'Avcı', 'Türk', 'Çakır', 'Ünal', 'Güneş', 'Karaca', 'Güler', 'Aktaş',
    'Keskin', 'Polat', 'Doğanay', 'Bulut', 'Tekin', 'Sarı', 'Yavuz', 'Çalışkan', 'Acar', 'Bozkurt',
    'Çoban', 'Ateş', 'Gül', 'Karaman', 'Uçar', 'Duman', 'Bayram', 'Aydemir', 'Taş', 'Akın',
    'Çınar', 'Kaplan', 'Özer', 'Sönmez', 'Gündüz', 'Işık', 'Köse', 'Akbaş', 'Erdem', 'Can',
    'Akgün', 'Karataş', 'Çevik', 'Güngör', 'Öz', 'Turan', 'Mutlu', 'Eren', 'Akbulut', 'Durmuş',
    'Çiftçi', 'Gök', 'Korkmaz', 'Altun', 'Sezer', 'Demirtaş', 'Gürbüz', 'Karadaş', 'Özçelik', 'Uysal',
    'Akyol', 'Baran', 'Coşkun', 'Duran', 'Ekinci', 'Fidan', 'Gür', 'İnce', 'Kalkan', 'Lale',
    'Mert', 'Nalçacı', 'Orhan', 'Peker', 'Rüzgar', 'Soylu', 'Toprak', 'Usta', 'Vural', 'Yaman',
    'Zengin', 'Akça', 'Alkan', 'Balcı', 'Bilir', 'Ceylan', 'Dağ', 'Erol', 'Fırat', 'Gökçe',
    'Hacıoğlu', 'İpek', 'Kartal', 'Levent', 'Meral', 'Narin', 'Ocak', 'Parlak', 'Sağlam', 'Tan',
    'Uğur', 'Varol', 'Yalçın', 'Zeybek', 'Akay', 'Albayrak', 'Başar', 'Bilgin', 'Cengiz', 'Demirel',
    'Efe', 'Genç', 'Hazar', 'İlhan', 'Keleş', 'Limon', 'Maden', 'Niyazi', 'Okay', 'Pehlivan',
    'Sancak', 'Tuna', 'Uzun', 'Varlı', 'Yiğit', 'Akbaba', 'Alptekin', 'Başkan', 'Biçer', 'Cihan',
    'Deniz', 'Ege', 'Gökalp', 'Işıklı', 'İnan', 'Kıran', 'Maviş', 'Okan', 'Pala', 'Sarıtaş',
    'Toker', 'Ünlü', 'Yağcı', 'Akdemir', 'Arı', 'Bayraktar', 'Boz', 'Çağlar', 'Dede', 'Elmas',
    'Göktaş', 'Işıtan', 'Karabulut', 'Kuş', 'Nalbant', 'Onay', 'Poyraz', 'Savaş', 'Tokgöz', 'Üstün',
    'Yağmur', 'Akdoğan', 'Arıkan', 'Bektaş', 'Bozdoğan', 'Çakmak', 'Dikmen', 'Ercan', 'Göktürk', 'İlter',
    'Karaduman', 'Kutlu', 'Okay', 'Seyhan', 'Tosun', 'Yüksel', 'Akgül', 'Arısoy', 'Bekiroğlu', 'Budak',
    'Çalık', 'Dinç', 'Ergün', 'Gözükara', 'Kahraman', 'Kutluğ', 'Önal', 'Sevinç', 'Tufan', 'Yüce',
    'Akıncı', 'Asil', 'Belli', 'Büyük', 'Çam', 'Dincer', 'Erkmen', 'Gültekin', 'Kandemir', 'Küçük',
    'Önen', 'Solak', 'Tuncer', 'Yücel', 'Akkaya', 'Atak', 'Berk', 'Cebeci', 'Çamur', 'Dursun',
    'Eroğlu', 'Gümüş', 'Kanat', 'Küçükali', 'Öner', 'Soydan', 'Turhan', 'Yükselen', 'Akkoyun', 'Atay',
    'Beşer', 'Ceyhun', 'Çanga', 'Dülger', 'Ertürk', 'Günay', 'Kantarcı', 'Macit', 'Özay', 'Soysal',
    'Tutak', 'Zafer', 'Akman', 'Ateşoğlu', 'Beyaz', 'Cömert', 'Çavuş', 'Eken', 'Eryılmaz', 'Günaydın',
    'Kaplan', 'Mete', 'Özbey', 'Sümer', 'Tüzün', 'Zorlu', 'Akpınar', 'Ayan', 'Bilge', 'Çay',
    'Ekici', 'Esen', 'Güney', 'Karahan', 'Metin', 'Özcan', 'Şen', 'Ulu', 'Aksu', 'Ayaz',
    'Bingöl', 'Çelebi', 'Ekmekçi', 'Esmer', 'Güven', 'Karakaş', 'Mızrak', 'Özden', 'Şener', 'Ulusoy',
    'Aktürk', 'Aybar', 'Birinci', 'Çetinkaya', 'Elçi', 'Eşsiz', 'Güzel', 'Karakaya', 'Mollaoğlu', 'Özdoğan',
    'Şengül', 'Uluç', 'Aladağ', 'Aydoğan', 'Bolat', 'Çiçek', 'Elmalı', 'Evren', 'Hancı', 'Karakoç',
    'Müftüoğlu', 'Özgen', 'Şentürk', 'Umur', 'Alagöz', 'Aydoğdu', 'Bostancı', 'Çiftlik', 'Emek', 'Eyüboğlu',
    'Hatipoğlu', 'Karakurt', 'Namlı', 'Özgül', 'Şimşir', 'Ural', 'Albay', 'Ayhan', 'Boyacı', 'Çil',
    'Emre', 'Fındık', 'Haydaroğlu', 'Karasu', 'Nazlı', 'Özgün', 'Taşçı', 'Uslu', 'Alici', 'Aykut',
    'Bozdemir', 'Çolak', 'Erbaş', 'Gazi', 'Horoz', 'Karayel', 'Oğuz', 'Özhan', 'Taşdemir', 'Uyar',
    'Alp', 'Ayrancı', 'Bozkaya', 'Dağdelen', 'Erbil', 'Gedik', 'Işıldar', 'Kardaş', 'Okur', 'Özkaya',
    'Taşkın', 'Uymaz', 'Altan', 'Azak', 'Bozkuş', 'Dal', 'Ercüment', 'Gezer', 'İlgezdi', 'Kargı',
    'Olgun', 'Özkul', 'Taşlı', 'Uz', 'Altay', 'Bacak', 'Bozkurtlu', 'Dalyan', 'Ergin', 'Göçer',
    'İmamoğlu', 'Kargıner', 'Onur', 'Özmen', 'Taştan', 'Uzel', 'Altın', 'Bağcı', 'Bölük', 'Damar',
    'Erkan', 'Göçmen', 'İnci', 'Kasap', 'Oruç', 'Özsoy', 'Tatlı', 'Ülger', 'Altınok', 'Bağıran',
    'Börü', 'Dayı', 'Erkılıç', 'Gökmen', 'İnönü', 'Kavak', 'Otlu', 'Öztuna', 'Tekeli', 'Ünlüer',
    'Altıntaş', 'Bakır', 'Buğday', 'Delice', 'Erman', 'Göksel', 'İrtem', 'Kavaklı', 'Öçal', 'Özyurt',
    'Tekgöz', 'Ünver', 'Anadol', 'Bal', 'Bülbül', 'Demirbaş', 'Erozan', 'Gökşen', 'İşler', 'Kayhan',
    'Önder', 'Paksoy', 'Temel', 'Üstüner', 'Andıç', 'Balaban', 'Candan', 'Demircan', 'Ersoy', 'Göktürk',
    'Kabadayı', 'Kelebek', 'Öngel', 'Palabıyık', 'Temiz', 'Varan', 'Apaydın', 'Balkan', 'Cebesoy', 'Demirci',
    'Ertaş', 'Gözcü', 'Kadıoğlu', 'Kemaloğlu', 'Önol', 'Pamuk', 'Tepe', 'Vatansever', 'Aral', 'Ballı',
    'Cengizhan', 'Demirkol', 'Eryıldız', 'Güçlü', 'Kahya', 'Kendirli', 'Örs', 'Pınar', 'Terzi', 'Yağız',
    'Aras', 'Barış', 'Ceran', 'Denizli', 'Eşref', 'Gülcü', 'Kalaycı', 'Kılıçoğlu', 'Özalp', 'Pirinç',
    'Tilki', 'Yakut', 'Arat', 'Baş', 'Cevahir', 'Dereli', 'Evcil', 'Güleryüz', 'Kalkanlı', 'Kına',
    'Özbek', 'Sabancı', 'Tiryaki', 'Yalman', 'Arıbaş', 'Başak', 'Cicioğlu', 'Derviş', 'Evin', 'Gülmez',
    'Kalyoncu', 'Kır', 'Özbilek', 'Sadık', 'Tok', 'Yamaner', 'Arman', 'Başaran', 'Cin', 'Deveci',
    'Eyüp', 'Gülşen', 'Kama', 'Kırmızı', 'Özbir', 'Sağır', 'Tokat', 'Yanık', 'Artvin', 'Başer',
    'Coşar', 'Dikici', 'Ezici', 'Gümüşay', 'Kamer', 'Kızıl', 'Özbudak', 'Sakarya', 'Toklu', 'Yaprak',
    'Aslanhan', 'Batmaz', 'Cumhur', 'Dilber', 'Fıratlı', 'Gümüşsoy', 'Kan', 'Koçak', 'Özçetin', 'Saka',
    'Topal', 'Yardımcı', 'Atılgan', 'Bayar', 'Çakıroğlu', 'Dilek', 'Filiz', 'Gündoğdu', 'Kanbur', 'Koçer',
    'Özdaş', 'Salman', 'Topçu', 'Yaşar', 'Atmaca', 'Bayındır', 'Çalıkhan', 'Dinçer', 'Geçit', 'Güneri',
    'Kandemiroğlu', 'Konak', 'Özel', 'Samancı', 'Topuz', 'Yazıcı', 'Avşar', 'Baykal', 'Çamlı', 'Dirik',
    'Gedikoğlu', 'Gürsoy', 'Kapucu', 'Konuk', 'Özen', 'Sarıkaya', 'Torun', 'Yener', 'Ay', 'Bayrak',
    'Çanakçı', 'Doğru', 'Girgin', 'Güvenç', 'Karaağaç', 'Kopuz', 'Özeren', 'Sarıkurt', 'Tosunoğlu', 'Yerlikaya',
    'Aydıner', 'Bayramoğlu', 'Çelikbaş', 'Dokumacı', 'Göç', 'Hacı', 'Karaaslan', 'Korucu', 'Özgür', 'Saygı',
    'Toy', 'Yeşil', 'Aykaç', 'Bedir', 'Çetiner', 'Dolu', 'Göçerli', 'Halıcı', 'Karabağ', 'Koyuncu',
    'Özkılınç', 'Sayın', 'Tufanbey', 'Yetiş', 'Ayrım', 'Beşikçi', 'Çiçekçi', 'Dönmez', 'Gökay', 'Hamzaoğlu',
    'Karabacak', 'Köksal', 'Özlem', 'Seçkin', 'Tuluk', 'Yıldıran', 'Azgın', 'Beyhan', 'Çobanlar', 'Duru',
    'Gökcan', 'Has', 'Karabey', 'Köroğlu', 'Öztoprak', 'Selçuk', 'Tunaer', 'Yılmazer', 'Babacan', 'Bıyık',
    'Dağlı', 'Durukan', 'Gökdal', 'Hatun', 'Karabulutlu', 'Kurtoğlu', 'Pak', 'Selvi', 'Tuncay', 'Yolcu',
    'Badem', 'Bilici', 'Dalgiç', 'Dülgeroğlu', 'Gökdeniz', 'Hayran', 'Karacaören', 'Kutay', 'Palaz', 'Semiz',
    'Tural', 'Yurdakul', 'Bahadır', 'Binici', 'Damla', 'Ecevit', 'Gökduman', 'Heper', 'Karadeniz', 'Kutluhan',
    'Parlar', 'Serin', 'Turgut', 'Yurtseven', 'Bakkal', 'Birkan', 'Dayıoğlu', 'Efehan', 'Gökhan', 'Hızlı',
    'Karadere', 'Kuzu', 'Pekmez', 'Seven', 'Türker', 'Yurttaş', 'Balabanlı', 'Bodur', 'Değirmenci', 'Ekiz',
    'Göktan', 'Horasan', 'Karagöz', 'Küçükoğlu', 'Pektaş', 'Sevimli', 'Türkoğlu', 'Zeytinoğlu', 'Barut',
    'Boran', 'Deligöz', 'Elçiçek', 'Gökyar', 'Hürriyet', 'Karahanlı', 'Macaroğlu', 'Pekün', 'Seyhanlı',
    'Türkmen', 'Zor', 'Başçı', 'Bozok', 'Demirhan', 'Elibol', 'Gözükaraoğlu', 'Işıler', 'Karakoyun', 'Marangoz',
    'Pekyavaş', 'Sezgin', 'Uçarlı', 'Zorba'
];

export const TURKISH_GIVEN_NAMES = toSet(GIVEN_NAMES);
export const TURKISH_SURNAMES = toSet(SURNAMES);

export function isKnownTurkishGivenName(value) {
    if (!value) return false;
    return TURKISH_GIVEN_NAMES.has(String(value).toLocaleLowerCase('tr-TR'));
}

export function isKnownTurkishSurname(value) {
    if (!value) return false;
    return TURKISH_SURNAMES.has(String(value).toLocaleLowerCase('tr-TR'));
}
